name: Build and Deploy

on:
  push:
    branches: [ main ]


jobs:
  uploadfiles:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - uses: /.github/actions/
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}