name: Build and Deploy

on:
  push:
    branches: [ main ]


jobs:
  uploadfiles:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - uses: ./.github/actions
        with:
          iam-role-arn: ${{ secrets.IAMROLE_GITHUB }}
          bucket-name: github-action-suresh
          filename: helloworld.py